fix issue for seek to position
bdlukaa/just_audio pull request #1
Opened 2022-07-03 11:07 UTC by AmirhosseinShk

on windows get nullPointer error when seek to position because get error when convert from int to int64 some times for small values and fix it now.

2022-07-03 20:45 UTC, bdlukaa commented
it sometimes fail when running the example app:

```terminal
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(position, the position argument can not be null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.seek (package:just_audio_platform_interface/method_channel_just_audio.dart:152:34)
<asynchronous suspension>
#3      AudioPlayer.seek (package:just_audio/just_audio.dart:1070:9)
<asynchronous suspension>
```

2022-07-04 06:54 UTC, AmirhosseinShk commented
huum, interesting , I'm agree with you , let's add int_64 as fall back and i think its could be ok

2022-07-05 23:34 UTC, bdlukaa requested changes

2022-07-05 23:34 UTC, bdlukaa commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int_64>(ValueOrNull(*args, "position"));
int_64 isn't a type.

```suggestion
            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
```

2022-07-07 18:07 UTC, bdlukaa reviewed
I guess it'd be better if we handle them separatedely!

2022-07-07 18:07 UTC, bdlukaa commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
the `position` parameter can not be changed type

2022-07-07 21:08 UTC, AmirhosseinShk commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
yeah , that my mistake let me separate them and fix it

2022-07-10 12:11 UTC, bdlukaa approved these changes

2022-07-10 12:12 UTC, merged

2022-07-14 09:46 UTC, VCasecnikovs commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
@bdlukaa, hi, when this update will be available in the pub.dev package?

2022-07-14 09:50 UTC, VCasecnikovs commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
seek still throws an error

2022-07-14 09:55 UTC, VCasecnikovs commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
Unhandled Exception: PlatformException(position, the position argument can not be null, null, null)

2022-07-14 10:47 UTC, AmirhosseinShk commented on just_audio_windows/windows/player.hpp
> +            position = std::get_if<int64_t>(ValueOrNull(*args, "position"));
hi , idk when this update release on pub dev , but u can use master branch from git

can u tell me ur senario and input type? we test it alot on flutter windows with different type and it's work fine